name: GitHub Actions
on: push
jobs:
  PremierJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Premier Job"
      - run: echo "FIN !"

  SecondJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Second Job"
      - run: echo "FIN !"
    needs:
      - PremierJob


