name: MEP-CD
on:
  workflow_dispatch:
    inputs:
      env_deploy:
        description: 'Environment to deploy'
        required: true
        default: 'dev'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{inputs.env_deploy == 'dev'}}
    steps:
      - run : echo "[D] Deploying to ${{inputs.env_deploy}} environment"

  deploy-preprod:
    runs-on: ubuntu-latest
    if: ${{inputs.env_deploy == 'preprod'}}
    steps:
      - run : echo "[PP] Deploying to ${{inputs.env_deploy}} environment"

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{inputs.env_deploy == 'prod'}}
    steps:
      - run : echo "[P] Deploying to ${{inputs.env_deploy}} environment"

  master_branch:
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
      - uses: actions/checkout@v4.1.1
      - run: echo "Deploying to master branch"


  job_deploy_complet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy complet"
      - name: echo prod
        if: ${{inputs.env_deploy == 'prod'}}
        run: echo "Deploy complet to prod"
      - name: echo preprod
        if: ${{inputs.env_deploy == 'preprod'}}
        run: echo "Deploy complet to preprod"
      - name: echo dev
        if: ${{inputs.env_deploy == 'dev'}}
        run: echo "Deploy complet to dev"
      - name: checkout master
        if: ${{github.ref == 'refs/heads/main'}}
        uses: actions/checkout@v4.1.1
