name: Test secrets / variables
on: push
jobs:
  display_values:
    runs-on: ubuntu-latest
    outputs:
      return-dyn: ${{ steps.etape_retour.output.return }}
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
          
      - name: etape_retour
        uses: actions/github-script@v7.0.1
        
        with:
          script:
            return "Chaine retournee";

  display_retour_etape:
    runs-on: ubuntu-latest
    needs: display_values
    steps:
      - run: ${{ needs.display_values.outputs.return-dyn }}
    
  
          
      
