name: Test secrets / variables
on: [merge_group]
jobs:
  display_values:
    runs-on: ubuntu-latest
    outputs:
      return-dyn: ${{ steps.id_etape_retour.outputs.result }}
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
          
      - name: etape_retour
        id: id_etape_retour
        uses: actions/github-script@v7.0.1
        
        with:
          script: return "Chaine retournee";

  display_retour_etape:
    runs-on: ubuntu-latest
    needs: display_values
    steps:
      - run: echo "${{ needs.display_values.outputs.return-dyn }}"
    
  
          
      
